 trigger:
 - main

 pool:
   vmImage: 'ubuntu-latest' 

 variables:
   imageName: 'new-test-docker'

 steps:
 - task: Docker@2
   displayName: Build an image
   inputs:
     repository: new_test
     command: build
     Dockerfile: Dockerfile